insert into countries values('AR','Argentina',2);
insert into countries values('AU','Australia',3);
insert into countries values('BE','Belgium',1);
insert into countries values('BR','Brazil',2);
insert into countries values('CA','Canada',2);
insert into countries values('CH','Switzerland',1);
insert into countries values('CN','China',3);
insert into countries values('DE','Germany',1);
insert into countries values('DK','Denmark',1);
insert into countries values('EG','Egypt',4);
insert into countries values('FR','France',1);
insert into countries values('HK','HongKong',3);
insert into countries values('IL','Israel',4);
insert into countries values('IN','India',3);
insert into countries values('IT','Italy',1);
insert into countries values('JP','Japan',3);
insert into countries values('KW','Kuwait',4);
insert into countries values('MX','Mexico',2);
insert into countries values('NG','Nigeria',4);
insert into countries values('NL','Netherlands',1);
insert into countries values('SG','Singapore',3);
insert into countries values('UK','United Kingdom',1);
insert into countries values('US','United States of America',2);
insert into countries values('ZM','Zambia',4);
insert into countries values('ZW','Zimbabwe',4);
select * from countries;